### "FreeEMS 144 Distributor wheel"
cam_pattern: even_72  # 72 holes on the outer ring, starts with off
cam_sector_offset: -0.25 # first state starts half a cam sector the zero position
crank_pattern: freeems_decoder # special inner ring: 1:off,8:on,2:off,7:on,3:off,6:on,4:off,5:on,5:off,4:on,6:off,3:on,7:off,2:on,8:off,1:on
